### ISSUE TITLE
Dump readable values to stdout

### ISSUE THREAD

**Issue by matschaffer** [myENA/consul-backinator#1]
I noticed that the `-dump` option provides values as base64 encoded.

Would be possible/preferable to display them as straight strings in the dump output?

**Comment by leprechau** [comment]
The -dump option simply returns the raw decrypted/decompressed output from the Consul API.  It is just an easy way to "view" your backup files.

-- Aaron

**Comment by matschaffer** [comment]
For sure. My thinking was that if we had multiple backup files it could be useful to see the full set of keys & values to confirm we're reloading the best possible backup. For the time being I came up with this:

```console
> consul-backinator -restore -dump |\
  jq -r '.[] | [.Key, .Value] | @sh' |\
  xargs -I{} -n1 sh -c 'echo $(echo {} | cut -d" " -f1)=$(echo {} | cut -d" " -f2 | base64 -d)'
```

But it's pretty roundabout compared with what I'm guessing it'd take to have the dump code show decoded values.

Maybe `-dump -decode` would be better?

**Comment by leprechau** [comment]
Got it.  So instead of just decoding would you actually prefer a "human readable" output?  Maybe something in ascii table format?

**Comment by matschaffer** [comment]
That sounds like a cool idea. I haven't put much time into brainstorming
formats but so long as it's diffable it should be good.

On Tuesday, 8 March 2016, Aaron Hurt <notifications@github.com> wrote:

> Got it. So instead of just decoding would you actually prefer a "human
> readable" output? Maybe something in ascii table format?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/myENA/consul-backinator/issues/1#issuecomment-193330158>
> .
>


-- 

-Mat

matschaffer.com

**Comment by leprechau** [comment]
I couldn't think of a nice way to use a table or other format with all the possible options for a data payload in a KV store.  I settled on just a very simple output format ...

```
Key: keyName
ValueHere and Here
and Here
Key: someOtherKey
more Values and Stuff
```

This should be greppable/diffable and give you approximately what you wanted.

**Comment by matschaffer** [comment]
Looks fantastic. Thanks!

**Comment by leprechau** [comment]
Hey,
Did you hear the latest news? You should definetely read more info here <http://phunadyci.nathansrealty.com/aeitjl>

Good wishes, 6155945334@mms.att.net
