### ISSUE TITLE
add -skip-tls option to disable tls host verification (useful for self signed certs)

### ISSUE THREAD

**Issue by vijaybandari** [myENA/consul-backinator#15]
Consul api does provides this option through [TLSConfig](https://github.com/hashicorp/consul/blob/master/api/api.go#L132).

**Comment by leprechau** [comment]
This can be accomplished currently by using the same method as the actual consul agent since it uses the same underlying API library.  It respects all the same environment variables including ```CONSUL_HTTP_SSL_VERIFY``` that can be set to false to skip certificate verification.

__Example__
```
CONSUL_HTTP_SSL_VERIFY=false consul-backinator ....
```

**Comment by leprechau** [comment]
@vijaybandari did that work for you?

**Comment by leprechau** [comment]
Closing this as it should be resolved with either the environment variable of the fixes in #16 and #18

**Comment by vijaybandari** [comment]
Yeah, it worked.
