### ISSUE TITLE
vault info in consul

### ISSUE THREAD

**Issue by mg03** [myENA/consul-backinator#2]
im using consul as a backend to store vault info.

all information in consul is stores under the vault/ tree in encrypted format.

1) We have keys with acls on them, Does your tool need the management acl in order to traverse and backup the key/values?
2) Will your tool support taking backup of encrypted values under the vault/ tree?
    Will the values be backed up in encrypted format?  If yes, once the values are restored , will it still work with the original vault?

regards
meher

**Comment by leprechau** [comment]
I'm not very familiar with Vault and have not used it myself but this tool does support consul ACL tokens which can be passed via the ```-token``` flag.  The data will be backed up and restored exactly as it appears in consul. The tool will not alter or modify your data in any way between backup and restore other than optional path transformations with the ```-transform``` flag.

**Comment by leprechau** [comment]
Did that answer your questions?

**Comment by mg03** [comment]
HI

I think so, ill try it out and let you know

regards
