### ISSUE TITLE
KV restore

### ISSUE THREAD

**Issue by samber** [myENA/consul-backinator#20]
Hi guys,

What about a copy-before-delete feature that would move KV under a `restore.bak/` prefix, prior to restore data ?!

**Comment by leprechau** [comment]
The restore doesn't actually delete currently unless you explicitly tell it to clear the tree before restoring.  It will however happily replace any existing keys.  I'm not sure adding a loop to move keys around inside the KV store is a valid solution to what should just be a CYA process from the admin (backup before you restore).

**Comment by leprechau** [comment]
Closing this PR as I don't currently see a need to implement this as an automated process.  Please re-open if you really think it's needed.
