### ISSUE TITLE
Add file to releases page with SHA256 sums

### ISSUE THREAD

**Issue by kostyrevaa** [myENA/consul-backinator#21]
to give users an extra sense of security that they have a real, untampered-with download.
Example: See the consul_0.6.4_SHA256SUMS file at https://releases.hashicorp.com/consul/0.6.4/
Would be great if you sign the file with a GPG key -- e.g.: consul_0.6.4_SHA256SUMS.sig

**Comment by leprechau** [comment]
I'll add that to the packaging script and push it with the next release.
