### ISSUE TITLE
[Feature] Add support for IAM instance profile

### ISSUE THREAD

**Issue by shamil** [myENA/consul-backinator#23]
Hi,

Thanks for the tool.
I've a feature request for S3 backup. Currently the S3 backup works by specifying AWS access/secret keys. Is it possible to add a feature that uses IAM instance profile where possible?

**Comment by leprechau** [comment]
@shamil Sorry for the really late reply.  I'll need to dig into IAM a bit as I'm honestly not that familiar with how it works.  I'll mark this as a feature request though and keep it open.

**Comment by leprechau** [comment]
@shamil I did some research and the library I'm currently using to provide S3 access doesn't appear to support IAM profiles.  I selected the (minio-go)[https://github.com/minio/minio-go] library for it's compact size and clean interface ... I'd be more than happy to review pull requests that used an alternative library though if this is an important feature for you.

**Comment by leprechau** [comment]
@shamil @baptiste-ls I pushed a new commit to master that uses the official AWS SDK instead of the minio client.  This should enable all AWS/S3 features including IAM profiles.  Would appreciate any testing or feedback you could offer.

**Comment by leprechau** [comment]
Closing and considering this feature request complete.
