### ISSUE TITLE
docker: Error response from daemon: oci runtime error: container_linux.go

### ISSUE THREAD

**Issue by Aamir010** [myENA/consul-backinator#29]
Can anyone please help me to resolve this error.

docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/local/bin/consul-backinator backup -file=consul.bak\": stat /usr/local/bin/consul-backinator backup -file=consul.bak: no such file or directory"

**Comment by leprechau** [comment]
Was this using the image from Docker hub?

**Comment by leprechau** [comment]
Tests on my laptop pulling the latest image:

```
snoopy:~ ahurt$ docker version
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        unknown-buildtime
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: false

snoopy:~ ahurt$ docker pull myena/consul-backinator
Using default tag: latest
latest: Pulling from myena/consul-backinator
88286f41530e: Pull complete
1336e754ef21: Pull complete
9ea78e190b27: Pull complete
Digest: sha256:18ecf4145a70d1c6215bb0bb88505cc36c093e264d48117c11b0b117ad7ca6a9
Status: Downloaded newer image for myena/consul-backinator:latest

snoopy:~ ahurt$ docker run myena/consul-backinator --version
1.6.1
```

**Comment by leprechau** [comment]
@Aamir010 This might also be related to these issues with Docker and systemd:

https://bugzilla.redhat.com/show_bug.cgi?id=1405131
https://github.com/moby/moby/issues/28109

Could you give more background on your platform?

**Comment by Aamir010** [comment]
Here's my Docker version.

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.1-ce
 Built:        Tue May 30 17:59:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   7392c3b/17.03.1-ce
 Built:        Tue May 30 17:59:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by Aamir010** [comment]
@leprechau Here is the steps we are performing.
 1. Create a Docker image from Dockerfile.
---------------
FROM myena/consul-backinator

ENTRYPOINT ["/usr/local/bin/consul-backinator backup -addr=10.0.1.50:8500 -file=s3://<my_access_key>:<my_secret_key>@<my_bucket_name>/consul_backup?region=us-west-2"]

2. Docker build -t aamir010/consul-backup .

3. docker run aamir010/consul-backup

And this will gives below error.

docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: "/usr/local/bin/consul-backinator backup -file=s3://<my_access_key>:<my_secret_key>@<my_bucket_name>/consul_backup?region=us-west-2": stat /usr/local/bin/consul-backinator backup -file=s3://<my_access_key>:<my_secret_key>@<my_bucket_name>/consul_backup?region=us-west-2: no such file or directory"

**Comment by leprechau** [comment]
@Aamir010 that's a proper error message then.  That's not the proper format for the entrypoint setting.  You are trying to tell docker to execute a process called: `/usr/local/bin/consul-backinator backup -file=s3://<my_access_key>:<my_secret_key>@<my_bucket_name>/consul_backup?region=us-west-2` which obviously doesn't exist.  You either need to rebuild using the proper entry point format for a command and arguments OR just use the official docker hub image with arguments.

Example:

`docker run myena/consul-backinator backup -addr=10.0.1.50:8500 -file=s3://<my_access_key>:<my_secret_key>@<my_bucket_name>/consul_backup?region=us-west-2`

**Comment by Aamir010** [comment]
Thanks @leprechau  it works.
