### ISSUE TITLE
error while backing up data to s3

### ISSUE THREAD

**Issue by nanidvps** [myENA/consul-backinator#31]
docker run myena/consul-backinator backup -addr=10.0.1.50:8500 -file=s3://access key id:secretaccesskey@anilmytest/Backup?region=us-west-2
[Error] Failed to backup key data: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
status code: 409, request id: 3F231DD26FB7B637, host id: sQDegGUjvnzlT5YH7lcwZzLHmZPd1gNUBLKrB65VPKgiifX1rImHJPexGjwa/kT41/Xi6RTLlv8=

**Comment by leprechau** [comment]
This is an issue with a new return code from `CreateBucket` as outlined in #30 ... we shouldn't fail on this error.

**Comment by leprechau** [comment]
@nanidvps Thank you for all the help.  Let me know if the new `latest` build fixes this once it finishes in Docker Hub: https://hub.docker.com/r/myena/consul-backinator/builds/
