### ISSUE TITLE
support for multiple address value (-add)

### ISSUE THREAD

**Issue by nanidvps** [myENA/consul-backinator#34]
Hello,

I am trying to pass an array of consul server but it gets failed, I think "-add" flag doesn't support array list.

**Comment by leprechau** [comment]
Is there a reason to expect the `-addr` operation to support multiple hosts?  Currently the `-addr` option in consul-backinator works the same as the standard consul client `-http-addr` option and `CONSUL_HTTP_ADDR` environment variable.
