### ISSUE TITLE
Unable to restore queries

### ISSUE THREAD

**Issue by michaelgrosstarget** [myENA/consul-backinator#36]
Hello,

I'm able to successfully backup kvs/acls/queries but when I try to restore it seems to only restore the kvs and acls (ignoring the queries).

consul-backinator v1.6.2
consul v0.9.3

```
# consul-backinator backup -file kvs.bak -acls acls.bak -queries query.bak -key [SECRET] -token [CONSUL_TOKEN]
2017/11/02 21:26:36 [Success] Backed up 1 keys from / to kvs.bak
2017/11/02 21:26:36 [Success] Backed up 3 ACL tokens from  to acls.bak
2017/11/02 21:26:36 [Success] Backed up 1 query definitions from  to query.bak
Keep your backup and signature files in a safe place.
You will need both to restore your data.
# consul-backinator restore -file kvs.bak -acls acls.bak -queries query.bak -key [SECRET] -token [CONSUL_TOKEN]
2017/11/02 21:26:59 [Success] Restored 1 keys from kvs.bak to /
2017/11/02 21:26:59 [Success] Restored 3 ACL tokens from acls.bak to
```

And if I try specifying only the queries to backup and restore, I'm able to successfully back them up but get an error regarding my command flags when trying to restore.
```
# consul-backinator backup -nokv -queries query.bak -key [SECRET] -token [CONSUL_TOKEN]
2017/11/02 21:33:41 [Success] Backed up 1 query definitions from  to query.bak
Keep your backup and signature files in a safe place.
You will need both to restore your data.
# consul-backinator restore -nokv -queries query.bak -key [SECRET] -token [CONSUL_TOKEN]
2017/11/02 21:33:54 [Error] Passing 'nokv' and an empty 'acls' file doesn't make any sense.  You should specify an 'acls' file when using the 'nokv' option.
```

Am I missing something in my command syntax?  Or has the restore queries functionality not been fully implemented yet?

Thank you,
Mike

**Comment by leprechau** [comment]
Good question, let me take a look.

**Comment by leprechau** [comment]
You're absolutely right, I added query backup but never put in the hook for the restore command even though I built a `restoreQueries` function.  I've fixed this locally and will push it upstream shortly.

**Comment by michaelgrosstarget** [comment]
Thanks Aaron. Appreciate the quick response.

**Comment by leprechau** [comment]
@michaelgrosstarget let me know if that fixes the issue ... feel free to reopen if it does not.

**Comment by leprechau** [comment]
I can also roll an intermediate release if you need a binary to download.

**Comment by michaelgrosstarget** [comment]
Works great - thanks again Aaron!
