### ISSUE TITLE
rpc error permission denied while restoring keys to consul

### ISSUE THREAD

**Issue by anil-aws** [myENA/consul-backinator#38]
i am trying to restore keys to consul using

docker run myena/consul-backinator restore -addr=<consul ip>:8500 -file=s3://access key id:secret id@consul-bakup/stage-consul/2017-12-13_09:00_consul.bak?region=us-west-2

and i am getting error: rpc error permission denied

**Comment by leprechau** [comment]
That error would be coming from the destination consul cluster.  Can you look at a `consul monitor -log-level=debug` while attempting the restore?

**Comment by leprechau** [comment]
Do you have ACLs enabled on the destination?

**Comment by anil-aws** [comment]
yes, we do have ACL's enabled on the destination

**Comment by leprechau** [comment]
You will need to pass an access token:

```

**Comment by anil-aws** [comment]
do i need to do this
docker run myena/consul-backinator restore -addr=:8500 -- token=<> --file=s3://access key id:secret id@consul-bakup/stage-consul/2017-12-13_09:00_consul.bak?region=us-west-2

Regards

**Comment by anil-aws** [comment]
okie got it thanks alot!

**Comment by leprechau** [comment]
Np, you can also set it in an environment variable using `CONSUL_HTTP_TOKEN`
