### ISSUE TITLE
Failed to backup ACL tokens: Unexpected response code: 403 (Permission denied) 

### ISSUE THREAD

**Issue by nani-ar** [myENA/consul-backinator#39]
hello, i am trying to backup ACLS without key value and i got the permission denied error, could you please help me with this

docker run myena/consul-backinator backup -nokv -acls -token=<consul master token> -addr=10.18.1.82:8500 -file=s3://key id:secret@consul-bakup/backup-consul/$(date +%F_%R)_consul.bak?region=us-west-2

i run the same command without -nokv and -acls and it backed up keys but i am not able to backup ACL's, am i doing something wrong?

**Comment by leprechau** [comment]
The documentation may not be clear but the `-acls` option expects a filename.  The exact command to backup just the ACLs (without keys) to an S3 location would be something like this:

```
consul-backinator backup -nokv -token=consul-access-token -addr=10.18.1.82:8500 -acls=s3://access-key:secret-key@consul-bakup/backup-consul/$(date +%F_%R)_acls.bak?region=us-west-2
```

**Comment by nani-ar** [comment]
worked, thanks for your quick response!

**Comment by leprechau** [comment]
Glad it worked, hope you enjoy the tool.
