### ISSUE TITLE
Tries to CreateBucket on an existing bucket.

### ISSUE THREAD

**Issue by the-maldridge** [myENA/consul-backinator#45]
I have a policy which allows the PutObject permission to the specific bucket where I store my backups.  I am running version 1.6.5 and observe in my cloudtrail logs that backinator is trying to create the bucket; this fails for hopefully obvious reasons.

At this point I'm out of things to troubleshoot as by all rights this should work, and some months ago it did (I'm sure something changed since then, but right now I haven't bisected our change lists to find what it was).

**Comment by leprechau** [comment]
You are correct.

https://github.com/myENA/consul-backinator/blob/master/common/writeS3.go#L37-L51

That shouldn't prevent the application from progressing though.  What exact error is being thrown?

**Comment by the-maldridge** [comment]
Upon further inspection, our backups are being made correctly, we just were thrown by the continuous errors in cloudtrail.  Closing this out.
